
---

- hosts: imagr_web_servers
  remote_user: ubuntu
  sudo: yes

  tasks:
     - name: update apt-get if needed
       apt: update_cache=yes cache_valid_time=3600
       register: update

     - name: pip install if needed
       action: apt pkg=python-pip
       register: pip

     - name: update from git
       git: repo=https://github.com/sazlin/cfpydev-imagr.git
            dest=~/imagr
            version=deployment
       register: git

     - name: install psycopg2 (because pip install doesn't work :/)
       shell: apt-get build-dep python-psycopg2 -y
       register: psycopg2

     - debug: msg={{ psycopg2.stdout }}

     - name: pip install requirements
       pip: requirements=~/imagr/requirements.txt
       register: requirements

     - debug: var=requirements
