
---

- hosts: imagr_web_servers
  remote_user: ubuntu
  sudo: yes

  tasks:
     - name: update apt-get if needed
       apt: update_cache=yes cache_valid_time=3600
       register: update

     - name: pip install if needed
       action: apt pkg=python-pip
       register: pip

     - name: destroy old directory
       command: rm -rf /home/ubuntu/imagr
       register: destroy

     - name: update from git
       git: repo=http://github.com/sazlin/cfpydev-imagr.git
            dest=/home/ubuntu/imagr
            version=deployment
       register: git

     - name: install psycopg2 (because pip install doesn't work :/)
       shell: apt-get build-dep python-psycopg2 -y
       register: psycopg2

     - name: pip install requirements
       pip: requirements=/home/ubuntu/imagr/requirements.txt
       register: requirements

     - name: dl and build uwsgi
       shell: CC=gcc pip install uwsgi

     - django_manage: >
              command=collectstatic
              app_path=/home/ubuntu/imagr

     - name: kill supervisor
       shell: killall -w supervisord
       ignore_errors: yes

     - name: install supervisor if needed
       action: apt pkg=supervisor
       register: supervisor

     - name: copy our uwsgi config
       synchronize: src=./uwsgi.ini dest=/home/ubuntu/uwsgi.ini

     - name: copy our supervisor config
       synchronize: src=./supervisor.conf dest=/etc/supervisor/conf.d/supervisord.conf

     - name: set up nginx
       apt: name=nginx state=present

     - name: backup nginx config
       shell: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.orig

     - name: copy our nginx config
       shell: mv ./imagr/nginx.conf /etc/nginx/sites-available/default
       notify:
          - restart nginx
          - restart supervisor

  handlers:
     - name: restart nginx
       action: service name=nginx state=restarted

     - name: restart supervisor
       shell: supervisord
       sudo: yes














